name: "Example"
description: "Receives file and generates output"
inputs:
  file-path: # id of input
    description: "Path to test script"
    required: false
    default: "test-file.js"
runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
